### ISSUE TITLE
Windows / Aufruf Contao Manager

### ISSUE THREAD

**Issue by fkaminski** [DieSchittigs/contao-dev-server#1]
Hallo,
ich versuche den Server zu nutzen. Das klappt soweit, jedoch wenn ich den Contao-Manager aufrufen möchte wird dieser nicht ausgeführt sondern zum Download angeboten. Ich habe den Server lokal installiert.
Windows7 / PHP 7.2.1 / NPM 5.8.0 /Chrome Browser
In einem Verzeichnis:
```
npm init
npm install --save @dieschittigs/contao-dev-server
npx contao-dev-server --production true
```
Und dann: http://127.0.0.1:9000/contao-manager.phar.php
In der Konsole steht nur: GET /contao-manager.phar.php
Wenn ich mein lokales xampp heranziehe geht es ...

**Comment by salvatore-falcone-vkd** [comment]
same here

**Comment by saibotd** [comment]
Leider nutzen wir hier keine Windows zum Entwickeln. In der Vergangenheit haben wir mit WSL ganz gute Erfahrungen gemacht: https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux
